name: Go Cross-Platform Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Install dependencies
        run: go mod tidy

      - name: Build application
        run: |
          if [ "${{ runner.os }}" = "Windows" ]; then
            go build -v -o system-fingerprint.exe .
          else
            go build -v -o system-fingerprint .
          fi
        shell: bash

      # ویندوز: آپلود exe
      - name: Upload artifact (Windows)
        if: runner.os == 'Windows'
        uses: actions/upload-artifact@v4
        with:
          name: fingerprint-windows
          path: system-fingerprint.exe
          if-no-files-found: error

      # لینوکس: آپلود باینری
      - name: Upload artifact (Linux)
        if: runner.os == 'Linux'
        uses: actions/upload-artifact@v4
        with:
          name: fingerprint-linux
          path: system-fingerprint
          if-no-files-found: error
