name: Go Cross-Platform Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        # تعریف تمام ترکیبات به صورت دستی با include
        include:
          - os: ubuntu-latest
            shell: bash
            output_name: system-fingerprint
            goos: linux

          - os: windows-latest
            shell: pwsh
            output_name: system-fingerprint.exe
            goos: windows

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Install dependencies
        run: go mod tidy

      - name: Build application
        shell: ${{ matrix.shell }}
        run: |
          go build -v -o ${{ matrix.output_name }} .

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: fingerprint-${{ matrix.os }}
          path: ${{ matrix.output_name }}
          if-no-files-found: error