name: Go Cross-Platform Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        # تعیین شل مناسب برای هر OS
        include:
          - os: ubuntu-latest
            shell: bash
          - os: windows-latest
            shell: pwsh

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Install dependencies
        run: go mod tidy

      - name: Build application
        shell: ${{ matrix.shell }}
        run: |
          # در لینوکس (bash)
          if [ "${{ runner.os }}" == "Linux" ]; then
            go build -v -o system-fingerprint .
          else
            # در ویندوز (PowerShell)
            go build -v -o system-fingerprint.exe .
          fi

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: fingerprint-${{ matrix.os }}
          path: |
            system-fingerprint*
          if-no-files-found: error